#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# mesa-labs documentation build configuration file, created by
# sphinx-quickstart on Wed Dec 27 11:54:03 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use pathlib.Path.resolve to make it absolute, like shown here.
#
import os
import sys
from importlib.metadata import version as importlib_version
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parents[1]))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'nbsphinx',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',
    'sphinx_prompt',
    'sphinx_math_dollar',
    'sphinx_mdinclude',
    'myst_nb',
    'sphinx.ext.napoleon',
    'IPython.sphinxext.ipython_console_highlighting']


# docstrings
autodoc_typehints = "none"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# always execute notebooks
env_skip_execute = os.getenv("SKIP_EXECUTE")


if not env_skip_execute:
    nb_execution_mode = "force"
else:
    nb_execution_mode = "off"

nbsphinx_allow_errors = True
nbsphinx_timeout = 1000

# myst-nb control of notebooks
nb_execution_timeout = 500
nb_execution_allow_errors = True
myst_enable_extensions = ["dollarmath"]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The main toctree document.
main_doc = 'index'

# General information about the project.
project = 'mesa-labs'

#html_logo = "logo.png"


# The short X.Y version.
version = "1.0"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["changelog.md"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Enable linking references to other projects' documentation.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'matplotlib': ('https://matplotlib.org/stable', None),
    "networkx": ('https://networkx.org/documentation/stable', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'sympy': ('https://docs.sympy.org/latest/', None),
    'yt': ('https://yt-project.org/doc', None),
    'unyt': ('https://unyt.readthedocs.io/en/stable', None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
}

# Don't include the extra CSS from sphinx-prompt when using the copy button
copybutton_exclude = 'style'


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "repository_url": "https://github.com/zingale/mesa-labs",
    "use_repository_button": True,
    "use_issues_button": True,
    "use_edit_page_button": True,
    "use_source_button": True,
    "repository_branch": "main",
    "launch_buttons": {
        "colab_url": "https://colab.research.google.com",
    },
    "path_to_docs": "docs/source",
    "logo": {
        "text": f"MESA Summer School Urca Labs",
    }
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ["myfile.css"]
